CREATE TABLE IF NOT EXISTS rag_index_state (
    id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    requested_revision BIGINT UNSIGNED NOT NULL DEFAULT 0,
    requested_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT IGNORE INTO rag_index_state (id, requested_revision) VALUES (1, 0);
