CREATE TABLE IF NOT EXISTS user_ranch_designs (
  user_id BIGINT PRIMARY KEY,
  design_json JSON NOT NULL,
  revision INT UNSIGNED NOT NULL DEFAULT 1,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ranch_design_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
