CREATE TABLE IF NOT EXISTS workbench_planning_preferences (
  user_id BIGINT NOT NULL PRIMARY KEY,
  preferences_json JSON NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
