CREATE TABLE IF NOT EXISTS learning_entries (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  course_id BIGINT NOT NULL,
  node_id VARCHAR(120) NOT NULL,
  kind VARCHAR(20) NOT NULL,
  title VARCHAR(120) NOT NULL,
  content TEXT NOT NULL,
  feeling VARCHAR(20) NOT NULL DEFAULT '',
  category VARCHAR(20) NOT NULL DEFAULT '',
  excerpt TEXT NOT NULL,
  status VARCHAR(20) NOT NULL,
  document_version CHAR(64) NOT NULL,
  metadata_json JSON NULL,
  request_key CHAR(36) NOT NULL,
  revision INT UNSIGNED NOT NULL DEFAULT 1,
  review_response TEXT NULL,
  reviewed_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_learning_request (user_id, request_key),
  KEY idx_learning_owner (user_id, course_id, node_id, id),
  KEY idx_learning_review (course_id, node_id, kind, status, id),
  CONSTRAINT fk_learning_owner FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_learning_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
