CREATE TABLE IF NOT EXISTS learning_assessment_attempts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  course_id BIGINT NOT NULL,
  node_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  question_id VARCHAR(120) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  question_version VARCHAR(64) NOT NULL,
  document_version CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  question_snapshot MEDIUMTEXT NOT NULL,
  answer_json TEXT NOT NULL,
  status VARCHAR(20) NOT NULL,
  verdict VARCHAR(20) NULL,
  is_official TINYINT(1) NOT NULL DEFAULT 0,
  score DOUBLE NULL,
  max_score DOUBLE NOT NULL,
  pass_score DOUBLE NOT NULL,
  feedback TEXT NOT NULL,
  grading_basis TEXT NOT NULL,
  reference_markdown MEDIUMTEXT NOT NULL,
  request_key CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  payload_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  supersedes_attempt_id BIGINT UNSIGNED NULL,
  reviewed_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_learning_assessment_request (user_id, request_key),
  KEY idx_learning_assessment_owner (user_id, course_id, node_id, id),
  KEY idx_learning_assessment_review (course_id, node_id, status, id),
  CONSTRAINT fk_learning_assessment_owner FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_learning_assessment_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  CONSTRAINT fk_learning_assessment_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
