#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

NODE_BINARY="${NODE_BINARY:-node}"
DEVELOPMENT_MYSQL_HOST="${DEVELOPMENT_MYSQL_HOST:-${BACKEND_IP:-${MYSQL_HOST:-}}}"
DEVELOPMENT_MYSQL_PORT="${DEVELOPMENT_MYSQL_PORT:-${MYSQL_PORT:-3306}}"
DEVELOPMENT_MYSQL_USER="${DEVELOPMENT_MYSQL_USER:-${MYSQL_USER:-}}"
DEVELOPMENT_MYSQL_PASSWORD="${DEVELOPMENT_MYSQL_PASSWORD-${MYSQL_PASSWORD:-}}"
DEVELOPMENT_MYSQL_DATABASE="${DEVELOPMENT_MYSQL_DATABASE:-${MYSQL_DATABASE:+${MYSQL_DATABASE}_development}}"
DEVELOPMENT_MYSQL_SOCKET="${DEVELOPMENT_MYSQL_SOCKET:-${MYSQL_SOCKET:-}}"

: "${DEVELOPMENT_MYSQL_HOST:?DEVELOPMENT_MYSQL_HOST or BACKEND_IP is required}"
: "${DEVELOPMENT_MYSQL_PORT:?DEVELOPMENT_MYSQL_PORT or MYSQL_PORT is required}"
: "${DEVELOPMENT_MYSQL_USER:?DEVELOPMENT_MYSQL_USER or MYSQL_USER is required}"
: "${DEVELOPMENT_MYSQL_DATABASE:?DEVELOPMENT_MYSQL_DATABASE or MYSQL_DATABASE is required}"

if [[ ! "$DEVELOPMENT_MYSQL_DATABASE" =~ ^[A-Za-z0-9_]+$ ]]; then
  echo "[deploy] DEVELOPMENT_MYSQL_DATABASE must contain only letters, numbers, and underscores" >&2
  exit 1
fi

DEVELOPMENT_MYSQL_ARGS=(-u "$DEVELOPMENT_MYSQL_USER")
if [[ -n "$DEVELOPMENT_MYSQL_SOCKET" ]]; then
  DEVELOPMENT_MYSQL_ARGS+=(--socket "$DEVELOPMENT_MYSQL_SOCKET")
else
  DEVELOPMENT_MYSQL_ARGS+=(
    --protocol=TCP
    -h "$DEVELOPMENT_MYSQL_HOST"
    -P "$DEVELOPMENT_MYSQL_PORT"
  )
fi

echo "[deploy] ensuring development database exists: $DEVELOPMENT_MYSQL_DATABASE"
MYSQL_PWD="$DEVELOPMENT_MYSQL_PASSWORD" mysql "${DEVELOPMENT_MYSQL_ARGS[@]}" <<SQL
CREATE DATABASE IF NOT EXISTS \`$DEVELOPMENT_MYSQL_DATABASE\`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;
SQL

echo "[deploy] applying development database migrations"
NODE_ENV="${NODE_ENV:-production}" \
MYSQL_HOST="$DEVELOPMENT_MYSQL_HOST" \
MYSQL_PORT="$DEVELOPMENT_MYSQL_PORT" \
MYSQL_USER="$DEVELOPMENT_MYSQL_USER" \
MYSQL_PASSWORD="$DEVELOPMENT_MYSQL_PASSWORD" \
MYSQL_DATABASE="$DEVELOPMENT_MYSQL_DATABASE" \
MYSQL_SOCKET="$DEVELOPMENT_MYSQL_SOCKET" \
  "$NODE_BINARY" development/apps/api/dist/core/database/migrate.js

echo "[deploy] development database migration complete"
